amf:
    sbi:
      - addr: 10.45.0.2
        port: 7777
    
    ngap:
      - addr: 10.46.0.2
        port: 38412
    
    guami:
      - plmn_id:
          mcc: 001
          mnc: 01
        amf_id:
          region: 2
          set: 1
          pointer: 0
    
    tai:
      - plmn_id:
          mcc: 001
          mnc: 01
        tac: 1
    
    plmn_support:
      - plmn_id:
          mcc: 001
          mnc: 01
        s_nssai:
          - sst: 1
    
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA2, NEA1 ]
    
    network_name:
        full: Open5GS
    
    mongo:
      uri: mongodb://mongodb:27017/open5gs
